#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -m abe
#PBS -l mem=4gb
#PBS -j oe
#PBS -A drh20_a_g_sc_default

# Get started

echo " "

echo "Job started on ‘hostname‘ at ‘date‘"

echo " "

#load in python

module purge

module load python/3.6.3-anaconda5.0.1

#go to the correct work directory

cd $PBS_O_WORKDIR

python 1_NL_Download_python.py

# Finish up

echo " "

echo "Job Ended at ‘date‘"

echo " "