#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -m abe
#PBS -l mem=6gb
#PBS -j oe
#PBS -A open


echo " "
echo " "
echo "Job started on `hostname` at `date`"

ml gcc/7.3.1
ml r/3.4
module use /gpfs/group/dml129/default/sw/modules

cd work/sw/gdal/spack/
source ./share/spack/setup-env.sh
ml gdal-3.0.4-gcc-7.3.1-ztomvd7 proj-6.2.0-gcc-7.3.1-3dqejei

cd $PBS_O_WORKDIR
Rscript 4_combineToShapefile.R

echo "Job Ended at `date`"
